"""Export IAU 2000A nutation series and equation-of-equinoxes
complementary terms into a pure-Python data module.

Source tables: IERS Conventions 2010 (as bundled by Skyfield).
"""
import os

from skyfield.functions import load_bundled_npy

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "engine", "astro_engine", "nutation_data.py")


def rows(arr):
    return [tuple(x.item() for x in row) for row in arr]


def main():
    a = load_bundled_npy("nutation.npz")
    lines = [
        '"""IAU 2000A nutation series (IERS Conventions 2010).',
        "",
        "Generated by tools/build_nutation.py. Do not edit.",
        "Units: coefficients in 0.1 microarcsecond.",
        '"""',
        "",
    ]

    def emit(name, value):
        lines.append("%s = %r" % (name, value))

    emit("NALS", rows(a["nals_t"]))
    emit("LS_LON", rows(a["lunisolar_longitude_coefficients"]))
    emit("LS_OBL", rows(a["lunisolar_obliquity_coefficients"]))
    emit("NAPL", rows(a["napl_t"]))
    emit("PL_LON", rows(a["nutation_coefficients_longitude"]))
    emit("PL_OBL", rows(a["nutation_coefficients_obliquity"]))
    emit("KE0", rows(a["ke0_t"]))
    emit("KE1", tuple(x.item() for x in a["ke1"]))
    emit("SE0_S", tuple(x.item() for x in a["se0_t_0"]))
    emit("SE0_C", tuple(x.item() for x in a["se0_t_1"]))
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", OUT, os.path.getsize(OUT))


if __name__ == "__main__":
    main()
